# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: podinfo
#   namespace: podinfo
# spec:
#   releaseName: podinfo
#   chart:
#     spec:
#       chart: podinfo
#       sourceRef:
#         kind: HelmRepository
#         name: podinfo
#         namespace: flux-system
#   interval: 5m
#   install:
#     remediation:
#       retries: 3
#   # Default values
#   # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
#   values:
#     cache: redis-master.redis:6379
#     ingress:
#       enabled: true
#       annotations:
#         kubernetes.io/ingress.class: nginx
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: GitRepository
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   # The interval at which to check the upstream for updates
#   interval: 10m
#   # The repository URL, can be a HTTP/S or SSH address
#   url: https://github.com/apatelGWS/flux2-kustomize-helm-example.git
#   # The Git reference to checkout and monitor for changes
#   # (defaults to master)
#   # For all available options, see:
#   # https://toolkit.fluxcd.io/components/source/api/#source.toolkit.fluxcd.io/v1beta1.GitRepositoryRef
#   ref:
#     branch: main
# ---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  # The interval at which to reconcile the Helm release
  interval: 10m
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: ./charts/podinfo
      # The reference to the GitRepository
      sourceRef:
        kind: GitRepository
        name: flux-system
        # Optional, defaults to the namespace of the HelmRelease
        namespace: flux-system
